
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abc
 */
public class add extends javax.swing.JFrame {
    int totalMeal = 0;
    /**
     * Creates new form add
     */
    public add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        pnl2 = new java.awt.Panel();
        btnMeals = new javax.swing.JLabel();
        btnFrooti = new javax.swing.JLabel();
        btnLemon = new javax.swing.JLabel();
        btnBeer = new javax.swing.JLabel();
        btnMilk = new javax.swing.JLabel();
        txtFrooti = new javax.swing.JTextField();
        txtBeer = new javax.swing.JTextField();
        txtMilk = new javax.swing.JTextField();
        txtLemon = new javax.swing.JTextField();
        pnl1 = new java.awt.Panel();
        btnMeals1 = new javax.swing.JLabel();
        btnMomos = new javax.swing.JLabel();
        btnChilli = new javax.swing.JLabel();
        btnBurger = new javax.swing.JLabel();
        btnHotDog = new javax.swing.JLabel();
        txtMomos = new javax.swing.JTextField();
        txtChilli = new javax.swing.JTextField();
        txtBurger = new javax.swing.JTextField();
        txtHotDog = new javax.swing.JTextField();
        pnl4 = new java.awt.Panel();
        button1 = new java.awt.Button();
        btnTotal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnReceipt = new javax.swing.JButton();
        pnl3 = new java.awt.Panel();
        label1 = new java.awt.Label();
        labelDrink = new java.awt.Label();
        labelMeal = new java.awt.Label();
        label4 = new java.awt.Label();
        labelTax = new java.awt.Label();
        textField1 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        txtCostDrinks = new javax.swing.JTextField();
        txtCostMeals = new javax.swing.JTextField();
        txtCostTotal = new javax.swing.JTextField();
        pnl5 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        panel1.setBackground(new java.awt.Color(255, 153, 153));
        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESTURANT MANAGEMENT SYSTEM");
        jLabel1.setToolTipText("");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl2.setBackground(new java.awt.Color(255, 204, 255));
        pnl2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnMeals.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMeals.setText("DRINKS");

        btnFrooti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFrooti.setText("Frooti");

        btnLemon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLemon.setText("Lemon Juice");

        btnBeer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBeer.setText("Beer");

        btnMilk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMilk.setText("Milk Shake");

        txtFrooti.setText("0");

        txtBeer.setText("0");

        txtMilk.setText("0");

        txtLemon.setText("0");

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnMeals))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLemon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBeer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMilk, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFrooti, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(34, 34, 34)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMilk)
                            .addComponent(txtBeer)
                            .addComponent(txtFrooti, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txtLemon))))
                .addContainerGap())
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMeals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFrooti)
                    .addComponent(txtFrooti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLemon)
                    .addComponent(txtLemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBeer)
                    .addComponent(txtBeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMilk)
                    .addComponent(txtMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl1.setBackground(new java.awt.Color(255, 204, 255));
        pnl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnMeals1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMeals1.setText("MEALS");

        btnMomos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMomos.setText("Chicken Momos ");

        btnChilli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChilli.setText("Chicken Chilli ");

        btnBurger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBurger.setText("Veg Burger");

        btnHotDog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHotDog.setText("Hot Dog");

        txtMomos.setText("0");

        txtChilli.setText("0");

        txtBurger.setText("0");

        txtHotDog.setText("0");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnMeals1))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMomos)
                            .addComponent(btnChilli, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBurger, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHotDog, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(34, 34, 34)
                        .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChilli)
                            .addComponent(txtHotDog)
                            .addComponent(txtBurger)
                            .addComponent(txtMomos))))
                .addContainerGap())
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMeals1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMomos)
                    .addComponent(txtMomos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChilli)
                    .addComponent(txtChilli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBurger)
                    .addComponent(txtBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHotDog)
                    .addComponent(txtHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl4.setBackground(new java.awt.Color(255, 204, 255));

        button1.setLabel("button1");

        btnTotal.setBackground(new java.awt.Color(255, 153, 153));
        btnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.setToolTipText("");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 153, 153));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 153, 153));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnReceipt.setBackground(new java.awt.Color(255, 153, 153));
        btnReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReceipt.setText("Receipt");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl4Layout.createSequentialGroup()
                    .addGap(158, 158, 158)
                    .addComponent(btnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(296, Short.MAX_VALUE)))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        pnl3.setBackground(new java.awt.Color(255, 204, 255));

        label1.setText("label1");

        labelDrink.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelDrink.setText("Cost of Drinks");

        labelMeal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelMeal.setName("Cost"); // NOI18N
        labelMeal.setText("Cost of Meals");

        label4.setText("label4");

        labelTax.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelTax.setText("Total");

        textField1.setText("textField1");

        textField3.setText("textField3");

        textField5.setText("textField5");

        txtCostDrinks.setText("0");

        txtCostMeals.setText("0");

        txtCostTotal.setText("0");
        txtCostTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCostMeals))
                .addGap(102, 102, 102)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCostDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                        .addComponent(labelTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                        .addComponent(txtCostTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCostMeals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCostTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelMeal.getAccessibleContext().setAccessibleName("");

        pnl5.setBackground(new java.awt.Color(255, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL RECEIPT");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(pnl5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {                                         
     HelperClass s = new HelperClass();
     s.momos = Double.parseDouble(txtMomos.getText());
     s.chilli = Double.parseDouble(txtChilli.getText());
     s.burger = Double.parseDouble(txtBurger.getText());
     s.hotdog = Double.parseDouble(txtHotDog.getText());
     String total = String.valueOf(s.getMeals());
     txtCostMeals.setText(total);
     s.frooti = Double.parseDouble(txtFrooti.getText());
     s.lemon = Double.parseDouble(txtLemon.getText());
     s.beer = Double.parseDouble(txtBeer.getText());
     s.milkShake = Double.parseDouble(txtMilk.getText());
     String total2 = String.valueOf(s.getDrinks());
     txtCostDrinks.setText(total2);
     txtCostTotal.setText(String.valueOf(s.getTotal()));
    }                                        

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        HelperClass h = new HelperClass();
        h.isExit();
    }                                       

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
            JTextField clear = null;
            for(Component c : pnl1.getComponents()){
                if(c.toString().contains("javax.swing.JTextField")){
                clear = (JTextField)c;
                clear.setText("0");
                }
            }
            for(Component c : pnl2.getComponents()){
            if(c.toString().contains("javax.swing.JTextField")){
            clear = (JTextField)c;
            clear.setText("0");
                }
            }
            for(Component c : pnl3.getComponents()){
            if(c.toString().contains("javax.swing.JTextField")){
            clear = (JTextField)c;
            clear.setText("0");
                }
            }
            txtArea.setText("");
            
    }                                        

    private void txtCostTotalActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        String selected = null;
        HelperClass s = new HelperClass();
     s.momos = Double.parseDouble(txtMomos.getText());
     s.chilli = Double.parseDouble(txtChilli.getText());
     s.burger = Double.parseDouble(txtBurger.getText());
     s.hotdog = Double.parseDouble(txtHotDog.getText());
     String total = String.valueOf(s.getMeals());
     s.frooti = Double.parseDouble(txtFrooti.getText());
     s.lemon = Double.parseDouble(txtLemon.getText());
     s.beer = Double.parseDouble(txtBeer.getText());
     s.milkShake = Double.parseDouble(txtMilk.getText());
     String total2 = String.valueOf(s.getDrinks());
     txtArea.append("YOUR TOTAL BILL \n-----------------------------\n");
        Calendar c = Calendar.getInstance();
        c.getTime();
        SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss");
        SimpleDateFormat date = new SimpleDateFormat("dd:mmm:yyyy");
        txtArea.append("Date: "+ date.format(c.getTime())+ "\n");
        txtArea.append("Time: " +time.format(c.getTime())+ "\n");
        txtArea.append("-----------------------------\n");
       if(s.momos != 0){
        txtArea.append(String.valueOf("Chicken Momos: "+ s.momos*s.costofMomos)+ "\n");
       }if(s.chilli != 0){
        txtArea.append(String.valueOf("Chicken chilli: "+ s.chilli* s.costofChilli)+ "\n");
       }if(s.burger != 0){
       txtArea.append(String.valueOf("Veg Burger: "+ s.burger * s.costofBurger)+ "\n");
       }if(s.hotdog != 0){
       txtArea.append(String.valueOf("Hot Dog: "+ s.hotdog * s.costofHotDog)+ "\n");
       }if(s.frooti != 0){
       txtArea.append(String.valueOf("Maaza Frooti: "+ s.frooti * s.costofFrooti)+ "\n");
       }if(s.lemon != 0){
       txtArea.append(String.valueOf("Lemon Juice: "+ s.lemon * s.costofLemon)+ "\n");
       }if(s.beer != 0){
       txtArea.append(String.valueOf("Beer: "+ s.beer * s.costofBeer)+ "\n");
       }if(s.milkShake != 0){
       txtArea.append(String.valueOf("Amul Milk Shake: "+ s.milkShake * s.costofMilkShake)+ "\n");
       }
       txtArea.append("-----------------------------\n");
       txtArea.append(String.valueOf("Total Meals: "+ s.getMeals())+ "\n");
       txtArea.append(String.valueOf("Total Drinks: "+ s.getDrinks())+"\n" );
       txtArea.append(String.valueOf("Total Amount: "+ s.getTotal())+"\n" );
       
      txtArea.append("-----------------------------\n");
      txtArea.append("HAVE A NICE DAY \n");
      txtArea.append("-----------------------------\n");
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel btnBeer;
    private javax.swing.JLabel btnBurger;
    private javax.swing.JLabel btnChilli;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel btnFrooti;
    private javax.swing.JLabel btnHotDog;
    private javax.swing.JLabel btnLemon;
    private javax.swing.JLabel btnMeals;
    private javax.swing.JLabel btnMeals1;
    private javax.swing.JLabel btnMilk;
    private javax.swing.JLabel btnMomos;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label4;
    private java.awt.Label labelDrink;
    private java.awt.Label labelMeal;
    private java.awt.Label labelTax;
    private java.awt.Panel panel1;
    private java.awt.Panel pnl1;
    private java.awt.Panel pnl2;
    private java.awt.Panel pnl3;
    private java.awt.Panel pnl4;
    private java.awt.Panel pnl5;
    private java.awt.TextField textField1;
    private java.awt.TextField textField3;
    private java.awt.TextField textField5;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtBeer;
    private javax.swing.JTextField txtBurger;
    private javax.swing.JTextField txtChilli;
    private javax.swing.JTextField txtCostDrinks;
    private javax.swing.JTextField txtCostMeals;
    private javax.swing.JTextField txtCostTotal;
    private javax.swing.JTextField txtFrooti;
    private javax.swing.JTextField txtHotDog;
    private javax.swing.JTextField txtLemon;
    private javax.swing.JTextField txtMilk;
    private javax.swing.JTextField txtMomos;
    // End of variables declaration                   
}
